Site/Chromascape/Models/InlineEditors/ImageUploaderEditor/ImageUploaderEditorViewModel.cs
using CMS.DocumentEngine;

namespace Chromascape.Models.InlineEditors.ImageUploaderEditor
{
    public class ImageUploaderEditorViewModel : InlineEditorsViewModel
    {
        /// <summary>
        /// Image.
        /// </summary>
        public DocumentAttachment Image { get; set; }


        /// <summary>
        /// Indicates if the message should be positioned absolutely for empty image.
        /// </summary>
        public bool UseAbsolutePosition { get; set; }


        /// <summary>
        /// Position of the message in case of absolute position.
        /// </summary>
        public PanelPositionEnum MessagePosition { get; set; } = PanelPositionEnum.Center;
    }
}

Site/Chromascape/Models/InlineEditors/ImageUploaderEditor/PanelPositionEnum.cs
namespace Chromascape.Models.InlineEditors.ImageUploaderEditor
{
    public enum PanelPositionEnum
    {
        /// <summary>
        /// Aligned to the top of the widget content.
        /// </summary>
        Top,


        /// <summary>
        /// Aligned to the center of the widget content.
        /// </summary>
        Center,


        /// <summary>
        /// Aligned to the bottom of the widget content.
        /// </summary>
        Bottom,

        /// <summary>
        /// Aligned to the right of the widget content.
        /// </summary>
        Right,

        /// <summary>
        /// Aligned to the left of the widget content.
        /// </summary>
        Left
    }
}

Site/Chromascape/Models/InlineEditors/InlineEditorsViewModel.cs
namespace Chromascape.Models.InlineEditors
{
    public abstract class InlineEditorsViewModel
    {
        public string PropertyName { get; set; }
    }
}

Site/Chromascape/Models/InlineEditors/TextEditor/TextEditorViewModel.cs
namespace Chromascape.Models.InlineEditors.TextEditor
{
    public class TextEditorViewModel : InlineEditorsViewModel
    {
        /// <summary>
        /// HTML formatted text.
        /// </summary>
        public string Text { get; set; }


        /// <summary>
        /// Indicates if the formatting is enabled for the editor.
        /// </summary>
        public bool EnableFormatting { get; set; } = true;
    }
}

Site/Chromascape/Controllers/InlineEditors/ImageUploaderController.cs
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.Membership;
using CMS.SiteProvider;
using Kentico.PageBuilder.Web.Mvc;
using Kentico.Web.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace Chromascape.Controllers.InlineEditors
{
    public class ImageUploaderController : Controller
    {
        private static readonly HashSet<string> allowedExtensions = new HashSet<string>(new[]
        {
            ".bmp",
            ".gif",
            ".ico",
            ".png",
            ".wmf",
            ".jpg",
            ".jpeg",
            ".tiff",
            ".tif"
        }, StringComparer.OrdinalIgnoreCase);

        [HttpPost]
        public JsonResult Upload(int pageId)
        {
            if (!HttpContext.Kentico().PageBuilder().EditMode)
            {
                throw new HttpException(403, "It is allowed to upload an image only when the page builder is in the edit mode.");
            }

            var page = DocumentHelper.GetDocument(pageId, null);
            if (!CheckPagePermissions(page))
            {
                throw new HttpException(403, "You are not authorized to upload an image to the page.");
            }

            var imageGuid = Guid.Empty;

            foreach (string requestFileName in Request.Files)
            {
                imageGuid = AddUnsortedAttachment(page, requestFileName);
            }

            return Json(new { guid = imageGuid });
        }

        private Guid AddUnsortedAttachment(TreeNode page, string requestFileName)
        {
            if (!(Request.Files[requestFileName] is HttpPostedFileWrapper file))
            {
                return Guid.Empty;
            }

            var directoryPath = EnsureUploadDirectory();
            var imagePath = GetTempFilePath(directoryPath, file);

            byte[] data = new byte[file.ContentLength];
            file.InputStream.Seek(0, SeekOrigin.Begin);
            file.InputStream.Read(data, 0, file.ContentLength);

            CMS.IO.File.WriteAllBytes(imagePath, data);

            var attachmentGuid = DocumentHelper.AddUnsortedAttachment(page, Guid.Empty, imagePath).AttachmentGUID;

            CMS.IO.File.Delete(imagePath);

            return attachmentGuid;
        }


        private string GetTempFilePath(string directoryPath, HttpPostedFileBase file)
        {
            var fileName = Path.GetFileName(file.FileName);
            if (string.IsNullOrEmpty(fileName))
            {
                throw new InvalidOperationException("Cannot upload file without file name.");
            }

            if (!allowedExtensions.Contains(Path.GetExtension(file.FileName)))
            {
                throw new InvalidOperationException("Cannot upload file of this type.");
            }

            return Path.Combine(directoryPath, fileName);
        }


        private string EnsureUploadDirectory()
        {
            var directoryPath = $"{Server.MapPath(@"~\")}App_Data\\Temp\\ImageUploader";

            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            return directoryPath;
        }


        private bool CheckPagePermissions(TreeNode page)
        {
            return page?.CheckPermissions(PermissionsEnum.Modify, SiteContext.CurrentSiteName, MembershipContext.AuthenticatedUser) ?? false;
        }
    }
}

Site/Chromascape/Views/Shared/InlineEditors/_ImageUploaderEditor.cshtml
@using Chromascape.Models.InlineEditors.ImageUploaderEditor
@model Chromascape.Models.InlineEditors.ImageUploaderEditor.ImageUploaderEditorViewModel


@{
    HtmlString GetActionUrl()
    {
        return Url.Kentico().AuthenticateUrl(Url.Action("Upload", "ImageUploader", new
        {
            pageId = Context.Kentico().PageBuilder().PageIdentifier
        }), false);
    }

    string GetContainerClass()
    {
        if (Model.Image != null)
        {
            return "uploader-container";
        }

        return Model.UseAbsolutePosition ? "uploader-empty-container absolute" : "uploader-empty-container";
    }

    string GetMessagePositionClass()
    {
        switch (Model.MessagePosition)
        {
            case PanelPositionEnum.Bottom:
                return "bottom";

            case PanelPositionEnum.Top:
                return "top";

            case PanelPositionEnum.Right:
                return "right";

            case PanelPositionEnum.Left:
                return "left";

            default:
                return "center";
        }
    }
}
@using (Html.Kentico().BeginInlineEditor("image-uploader-editor", Model.PropertyName,
    new
    {
        @class = "image-uploader-editor",
        data_url = GetActionUrl().ToString()
    }))
{
    <div class="@GetContainerClass()">
        <div class="uploader">
            <div class="dz-message @GetMessagePositionClass()">
                <i class="icon-arrow-up-line"></i>
                <div>
                    @Html.GetUIString("Drag and drop your image here")
                </div>
            </div>
        </div>
    </div>
}

Site/Chromascape/Views/Shared/InlineEditors/_TextEditor.cshtml
@model Chromascape.Models.InlineEditors.TextEditor.TextEditorViewModel

@using (Html.Kentico().BeginInlineEditor("text-editor", Model.PropertyName,
    new
    {
        @class = "text-editor",
        data_enable_formatting = Model.EnableFormatting.ToString()
    }))
{
    @Html.Raw(Model.Text)
}