Site/Chromascape/Controllers/SearchController.cs
using Business.DependencyInjection;
using Chromascape.Models;
using Chromascape.Models.Search;
using CMS.Membership;
using CMS.Search;
using System;
using System.Web.Mvc;
using Kentico.PageBuilder.Web.Mvc;
using Kentico.Web.Mvc;

namespace Chromascape.Controllers
{
    public class SearchController : BaseController
    {
        IBusinessDependencies _busDeps { get; }

        public SearchController(IBusinessDependencies businessDependencies) : base(businessDependencies)
        {
            _busDeps = businessDependencies;
        }

        // Adds the smart search indexes that will be used to perform searches
        public static readonly string[] searchIndexes = new string[] { "ChromaScapeSiteIndex" };
        // Sets the limit of items per page of search results
        private const int PAGE_SIZE = 10;

        public ActionResult SearchIndex(string searchText)
        {
            PageViewModel model = GetPageViewModel("/Home");

            model.SearchVM = new SearchViewModel();

            // Displays the search page without any search results if the query is empty
            if (String.IsNullOrWhiteSpace(searchText))
                return View(model);

            // Searches the specified index and gets the matching results
            SearchParameters searchParameters = SearchParameters.PrepareForPages(searchText, searchIndexes, 1, PAGE_SIZE, MembershipContext.AuthenticatedUser, "en-us", true);
            SearchResult searchResult = SearchHelper.Search(searchParameters);

            // Creates a model with the search result items
            model.SearchVM.Items = searchResult.Items;
            model.SearchVM.Query = searchText;

            // Initializes the page builder with the DocumentID of the page
            HttpContext.Kentico().PageBuilder().Initialize(1);

            return View(model);
        }
    }
}

Site/Chromascape/Views/Shared/_LayoutPage.cshtml
@using Kentico.PageBuilder.Web.Mvc
@using Kentico.Web.Mvc
@using Kentico.Activities.Web.Mvc

@model Chromascape.Models.PageViewModel

<!DOCTYPE html>

<html>
<head>
    <title>@Model.Metadata.PageTitle</title>
    <meta name="keywords" content="@Model.Metadata.Keywords" />
    <meta name="description" content="@Model.Metadata.Description" />


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <link href="~/styles/slick-theme.css" rel="stylesheet" />
    <link href="~/styles/slick.css" rel="stylesheet" />
    <link href="~/styles/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
    @*<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-XxNLWSzCxOe/CFcHcAiJAZ7LarLmw3f4975gOO6QkxvULbGGNDoSOTzItGUG++Q+" crossorigin="anonymous">*@
    <link href="~/styles/all.min.css" rel="stylesheet" />
    <link href="~/styles/fontawesome.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300i,700|Open+Sans:400,400i,700" rel="stylesheet">
    <link href="~/styles/main.css" rel="stylesheet" />
    <link href="~/styles/navigator.css" rel="stylesheet" />

    <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-TZHJQZH');
    </script>
    <!-- End Google Tag Manager -->

    <script src="~/scripts/jquery-3.3.1.min.js"></script>
    <script src="~/scripts/bootstrap/bootstrap.min.js"></script>

    @Html.Kentico().PageBuilderStyles()

</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TZHJQZH"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <!--[if IE]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <header id="header">
        <div class="header-top d-none d-md-block">
            <div class="container">
                <ul class="utility-nav">
                    <li><a href="@Model.SiteHeader.ContactUsUrl">@Model.SiteHeader.ContactUsText</a></li>
                    <li>
                        <a href="tel:@Model.SiteHeader.PhoneNumberText.Replace(")", "").Replace("(", "").Replace("-", "").Replace(" ", "")">
                            @Model.SiteHeader.PhoneNumberText
                        </a>
                    </li>
                    <li class="header-search">
                        @using (Html.BeginForm("SearchIndex", "Search", FormMethod.Get))
                        {
                            <span class="header-search-icon"></span>
                            <span class="header-search-input">
                                <input type="text" name="searchtext" placeholder="Search...">
                                <button class="btn btn-submit">Submit</button>
                            </span>
                        }
                    </li>
                </ul>
            </div>
        </div>
        <div class="header-bottom bg-ink">
            <div class="container">
                <a href="/" class="header-logo">
                    <img src="@Url.Content(Model.SiteHeader.LogoImage.GetPath())" alt="Chromascape Logo">
                </a>
                <div class="mobile-nav-toggle" id="mobile-nav-toggle">
                    <i class="fal fa-times"></i>
                    <img src="~/images/mobile-toggle-icon.svg" alt="">
                </div>
                <ul class="primary-nav">
                    @if (Model.MainMenuFolder.MenuItems != null && Model.MainMenuFolder.MenuItems.Count > 0)
                    {
                        foreach (var menuItem in Model.MainMenuFolder.MenuItems)
                        {
                            string linkTarget = (menuItem.LinkTarget) ? "_blank" : "";

                            if (menuItem.SubItems == null || menuItem.SubItems.Count == 0)
                            {
                                <li><a target="@linkTarget" href="@menuItem.Url">@menuItem.Name</a></li>
                            }

                            if (menuItem.SubItems != null && menuItem.SubItems.Count > 0)
                            {
                                <li class="has-children">
                                    <span class="mobile-nav-children-toggle"><i class="fas fa-chevron-right"></i></span>
                                    <a target="@linkTarget" href="@menuItem.Url" class="toggle-children">
                                        @menuItem.Name
                                    </a>
                                    <ul class="lvl-2">
                                        @foreach (var child in menuItem.SubItems)
                                        {
                                            string childLinkTarget = (child.LinkTarget) ? "_blank" : "";

                                            <li>
                                                <a target="@childLinkTarget" href="@child.Url">@child.Name</a>

                                                @if (child.SubItems != null && child.SubItems.Count > 0)
                                                {
                                                    <ul class="lvl-3">
                                                        @foreach (var grandChild in child.SubItems)
                                                        {
                                                            string grandChildLinkTarget = (grandChild.LinkTarget) ? "_blank" : "";

                                                            <li><a target="@grandChildLinkTarget" href="@grandChild.Url">@grandChild.Name</a></li>
                                                        }
                                                    </ul>
                                                }
                                            </li>
                                        }
                                    </ul>
                                </li>
                            }
                        }
                    }
                </ul>
                <a href="@Model.SiteHeader.CTAButtonUrl" class="btn btn-orange">@Model.SiteHeader.CTAButtonText</a>
            </div>
        </div>
    </header>

    @if (Model.ShowBreadcrumbs)
    {
        <nav aria-label="breadcrumb">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    @foreach (var link in Model.Breadcrumbs)
                    {
                        if (!link.IsActive)
                        {
                            <li class="breadcrumb-item"><a href="@link.Url">@link.Name</a></li>
                        }

                        if (link.IsActive)
                        {
                            <li class="breadcrumb-item active" aria-current='page'>@link.Name</li>
                        }
                    }
                </ol>
            </div>
        </nav>
    }

    @RenderBody()

    <footer class="footer">
        <div class="container py-5">
            <div class="row">
                <div class="col-sm-12 col-md-3">
                    <ul class="list-unstyled footer-links">
                        @if (Model.FooterMenuFolder.MenuItems != null && Model.FooterMenuFolder.MenuItems.Count > 0)
                        {
                            foreach (var menuItem in Model.FooterMenuFolder.MenuItems)
                            {
                                <li><a href="@menuItem.Url" class="h5"><strong>@menuItem.Name</strong></a></li>
                            }
                        }
                    </ul>
                </div>
                <div class="col-sm-12 col-md-3">
                    <div class="footer-contact">
                        <h5><strong>@Model.SiteFooter.ContactUsHeader</strong></h5>
                        @Html.Raw(Model.SiteFooter.ContactUsContent)
                    </div>
                </div>
                <div class="col-sm-12 col-md-3">
                    <h5><strong>FOLLOW US</strong></h5>
                    <ul class="list-unstyled list-inline follow-links">
                        @if (Model != null && Model.SocialLinks != null && Model.SocialLinks.Count > 0)
                        {
                            foreach (var link in Model.SocialLinks)
                            {
                                <li class="list-inline-item">
                                    <a href="@link.Url">
                                        <i class="fab @link.Icon"></i>
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                    <p>&copy; 2019 Chromascape, All rights reserved.</p>
                </div>
                <div class="col-sm-12 col-md-3">
                    <a href="@Model.SiteFooter.CTAButtonUrl" class="btn btn-orange">@Model.SiteFooter.CTAButtonText</a>
                </div>
            </div>
        </div>
    </footer>

    @Html.Kentico().PageBuilderScripts()

    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
    <script>
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "#000"
                },
                "button": {
                    "background": "#069abc"
                }
            }
        });
    </script>

    <script src="~/scripts/all.min.js"></script>
    <script src="~/scripts/slick.min.js"></script>
    <script src="~/scripts/main.js"></script>

    @Scripts.Render(Url.RouteUrl("KenticoLogActivityScript"))


    @*@Html.Kentico().ActivityLoggingScript()*@
</body>
</html>

Site/Chromascape/Views/Shared/_LayoutPageAlternate.cshtml
@using Kentico.Web.Mvc


@model Chromascape.Models.PageViewModel

<!DOCTYPE html>

<html>
<head>
    <title>@Model.Metadata.PageTitle</title>
    <meta name="keywords" content="@Model.Metadata.Keywords" />
    <meta name="description" content="@Model.Metadata.Description" />


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <link href="~/styles/slick-theme.css" rel="stylesheet" />
    <link href="~/styles/slick.css" rel="stylesheet" />
    <link href="~/styles/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
    @*<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-XxNLWSzCxOe/CFcHcAiJAZ7LarLmw3f4975gOO6QkxvULbGGNDoSOTzItGUG++Q+" crossorigin="anonymous">*@
    <link href="~/styles/all.min.css" rel="stylesheet" />
    <link href="~/styles/fontawesome.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300i,700|Open+Sans:400,400i,700" rel="stylesheet">
    <link href="~/styles/main.css" rel="stylesheet" />
    <link href="~/styles/navigator.css" rel="stylesheet" />

    <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-TZHJQZH');
    </script>
    <!-- End Google Tag Manager -->

    <script src="~/scripts/jquery-3.3.1.min.js"></script>
    <script src="~/scripts/bootstrap/bootstrap.min.js"></script>

</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TZHJQZH"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <!--[if IE]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <header id="header">
        <div class="header-top d-none d-md-block">
            <div class="container">
                <ul class="utility-nav">
                    <li><a href="@Model.SiteHeader.ContactUsUrl">@Model.SiteHeader.ContactUsText</a></li>
                    <li>
                        <a href="tel:@Model.SiteHeader.PhoneNumberText.Replace(")", "").Replace("(", "").Replace("-", "").Replace(" ", "")">
                            @Model.SiteHeader.PhoneNumberText
                        </a>
                    </li>
                    <li class="header-search">
                        @using (Html.BeginForm("SearchIndex", "Search", FormMethod.Get))
                        {
                            <span class="header-search-icon"></span>
                            <span class="header-search-input">
                                <input type="text" name="searchtext" placeholder="Search...">
                                <button class="btn btn-submit">Submit</button>
                            </span>
                        }
                    </li>
                </ul>
            </div>
        </div>
        <div class="header-bottom bg-ink">
            <div class="container">
                <a href="/" class="header-logo">
                    <img src="@Url.Content(Model.SiteHeader.LogoImage.GetPath())" alt="Chromascape Logo">
                </a>
                <div class="mobile-nav-toggle" id="mobile-nav-toggle">
                    <i class="fal fa-times"></i>
                    <img src="~/images/mobile-toggle-icon.svg" alt="">
                </div>
                <ul class="primary-nav">
                    @if (Model.MainMenuFolder.MenuItems != null && Model.MainMenuFolder.MenuItems.Count > 0)
                    {
                        foreach (var menuItem in Model.MainMenuFolder.MenuItems)
                        {
                            if (menuItem.SubItems == null || menuItem.SubItems.Count == 0)
                            {
                                <li><a href="@menuItem.Url">@menuItem.Name</a></li>
                            }

                            if (menuItem.SubItems != null && menuItem.SubItems.Count > 0)
                            {
                                <li class="has-children">
                                    <span class="mobile-nav-children-toggle"><i class="fas fa-chevron-right"></i></span>
                                    <a href="@menuItem.Url" class="toggle-children">
                                        @menuItem.Name
                                    </a>
                                    <ul class="lvl-2">
                                        @foreach (var child in menuItem.SubItems)
                                        {
                                            <li>
                                                <a href="@child.Url">@child.Name</a>

                                                @if (child.SubItems != null && child.SubItems.Count > 0)
                                                {
                                                    <ul class="lvl-3">
                                                        @foreach (var grandChild in child.SubItems)
                                                        {
                                                            <li><a href="@grandChild.Url">@grandChild.Name</a></li>
                                                        }
                                                    </ul>
                                                }
                                            </li>
                                        }
                                    </ul>
                                </li>
                            }
                        }
                    }
                </ul>
                <a href="@Model.SiteHeader.CTAButtonUrl" class="btn btn-orange">@Model.SiteHeader.CTAButtonText</a>
            </div>
        </div>
    </header>

    @if (Model.ShowBreadcrumbs)
    {
        <nav aria-label="breadcrumb">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    @foreach (var link in Model.Breadcrumbs)
                    {
                        if (!link.IsActive)
                        {
                            <li class="breadcrumb-item"><a href="@link.Url">@link.Name</a></li>
                        }

                        if (link.IsActive)
                        {
                            <li class="breadcrumb-item active" aria-current='page'>@link.Name</li>
                        }
                    }
                </ol>
            </div>
        </nav>
    }

    @RenderBody()

    <footer class="footer">
        <div class="container py-5">
            <div class="row">
                <div class="col-sm-12 col-md-3">
                    <ul class="list-unstyled footer-links">
                        @if (Model.FooterMenuFolder.MenuItems != null && Model.FooterMenuFolder.MenuItems.Count > 0)
                        {
                            foreach (var menuItem in Model.FooterMenuFolder.MenuItems)
                            {
                                <li><a href="@menuItem.Url" class="h5"><strong>@menuItem.Name</strong></a></li>
                            }
                        }
                    </ul>
                </div>
                <div class="col-sm-12 col-md-3">
                    <div class="footer-contact">
                        <h5><strong>@Model.SiteFooter.ContactUsHeader</strong></h5>
                        @Html.Raw(Model.SiteFooter.ContactUsContent)
                    </div>
                </div>
                <div class="col-sm-12 col-md-3">
                    <h5><strong>FOLLOW US</strong></h5>
                    <ul class="list-unstyled list-inline follow-links">
                        @if (Model != null && Model.SocialLinks != null && Model.SocialLinks.Count > 0)
                        {
                            foreach (var link in Model.SocialLinks)
                            {
                                <li class="list-inline-item">
                                    <a href="@link.Url">
                                        <i class="fab @link.Icon"></i>
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                    <p>&copy; 2019 Chromascape, All rights reserved.</p>
                </div>
                <div class="col-sm-12 col-md-3">
                    <a href="@Model.SiteFooter.CTAButtonUrl" class="btn btn-orange">@Model.SiteFooter.CTAButtonText</a>
                </div>
            </div>
        </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
    <script>
    window.cookieconsent.initialise({
    "palette": {
        "popup": {
        "background": "#000"
        },
        "button": {
        "background": "#069abc"
        }
    }
    });
    </script>

    <script src="~/scripts/all.min.js"></script>
    <script src="~/scripts/slick.min.js"></script>
    <script src="~/scripts/main.js"></script>
</body>
</html>